---
- name: Copy SSH private key for kolla-ansible
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../{{ kolla_ssh_private_key }}"
    dest: "{{ kolla_config_dir }}/ssh_key"
    mode: '0600'

- name: Disable SSH host key checking for kolla-ansible
  ansible.builtin.copy:
    dest: "{{ kolla_config_dir }}/ansible.cfg"
    content: |
      [defaults]
      host_key_checking = False
      [ssh_connection]
      ssh_args = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    mode: '0644'

- name: Template globals.yml
  ansible.builtin.template:
    src: globals.yml.j2
    dest: "{{ kolla_config_dir }}/globals.yml"
    mode: '0644'

- name: Template Kolla multinode inventory
  ansible.builtin.template:
    src: kolla_inventory.ini.j2
    dest: "{{ kolla_config_dir }}/multinode"
    mode: '0644'
