---
- name: Check if passwords.yml already exists
  ansible.builtin.stat:
    path: "{{ kolla_config_dir }}/passwords.yml"
  register: passwords_file

- name: Copy default passwords.yml
  ansible.builtin.copy:
    src: "{{ kolla_venv_path }}/share/kolla-ansible/etc_examples/kolla/passwords.yml"
    dest: "{{ kolla_config_dir }}/passwords.yml"
    mode: '0600'
    remote_src: yes
  when: not passwords_file.stat.exists

- name: Generate passwords with kolla-genpwd
  ansible.builtin.command:
    cmd: "{{ kolla_venv_path }}/bin/kolla-genpwd -p {{ kolla_config_dir }}/passwords.yml"
  when: not passwords_file.stat.exists
