# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: ndknitor
  description: Kubernetes cluster setup (kubeadm init, control plane join, worker join)
  license: MIT-0
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - kubernetes
    - k8s
    - kubeadm
dependencies: []
