---
- name: Install dependencies
  apt:
    name:
      - tar
      - curl
      - openssl
    state: present
    update_cache: yes

- name: Download etcd
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd.tar.gz"

- name: Extract etcd
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Include certificate generation
  include_tasks: certs.yml

- name: Deploy systemd unit
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Enable and start etcd
  systemd:
    name: etcd
    state: started
    enabled: yes
