---
- name: Pick rules for this host (host-specific or fallback to all)
  set_fact:
    fw_rules: "{{ firewall_rules[inventory_hostname] | default(firewall_rules['all']) }}"

- name: Ensure DOCKER-USER chain exists
  ansible.builtin.command: iptables -N DOCKER-USER
  ignore_errors: yes

- name: Flush DOCKER-USER chain (purge by default)
  ansible.builtin.command: iptables -F DOCKER-USER

- name: Apply Docker firewall rules
  ansible.builtin.iptables:
    chain: DOCKER-USER
    protocol: "{{ item.protocol }}"
    source: "{{ item.source }}"
    destination_port: "{{ item.destination_port }}"
    jump: ACCEPT
    comment: "Allow {{ item.source }} to access Docker port {{ item.destination_port }}"
  loop: "{{ fw_rules }}"
  loop_control:
    label: "{{ item.destination_port }}/{{ item.protocol }}"

- name: Block all other access to allowed Docker ports
  ansible.builtin.iptables:
    chain: DOCKER-USER
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.destination_port }}"
    jump: DROP
    comment: "Block other access to Docker port {{ item.destination_port }}"
  loop: "{{ fw_rules }}"
  loop_control:
    label: "{{ item.destination_port }}/{{ item.protocol }}"