all:
  hosts:
    kn1.ndkn.local:
      ansible_host: 192.168.56.101
    kn2.ndkn.local:
      ansible_host: 192.168.56.102
    kn3.ndkn.local:
      ansible_host: 192.168.56.103
  children:
    etcd:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    keepalived:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    docker:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local: