all:
  hosts:
    kn1.ndkn.local:
      ansible_host: 192.168.56.101
    kn2.ndkn.local:
      ansible_host: 192.168.56.102
    kn3.ndkn.local:
      ansible_host: 192.168.56.103
    kn4.ndkn.local:
      ansible_host: 192.168.56.104
    kn5.ndkn.local:
      ansible_host: 192.168.56.105
  children:
    etcd:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    keepalived:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    docker:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    k8s_control_plane:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    k8s_worker:
      hosts:
        kn4.ndkn.local:
        kn5.ndkn.local:
    openstack_controller:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    openstack_storage:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    openstack_compute:
      hosts:
        kn4.ndkn.local:
        kn5.ndkn.local:
    ceph_mon:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
    ceph_osd:
      hosts:
        kn1.ndkn.local:
        kn2.ndkn.local:
        kn3.ndkn.local:
