- name: Deploy etcd cluster
  hosts: etcd
  become: true
  vars:
    version: "3.5.13"
    download_url: "https://github.com/etcd-io/etcd/releases/download/v{{ version }}/etcd-v{{ version }}-linux-amd64.tar.gz"
    install_dir: /usr/local/bin
    data_dir: /var/lib/etcd
    user: etcd
    group: etcd
  roles:
    - etcd