- name: Manage firewall in Docker with iptables
  hosts: all
  become: yes
  vars:
    firewall_rules:
      all:
        - { protocol: tcp, destination_port: 80, source: "192.168.56.0/24" }
      etcd:
        - { protocol: tcp, destination_port: 2379, source: "0.0.0.0/0" }
        - { protocol: tcp, destination_port: 2380, source: "0.0.0.0/0" }
  roles:
    - firewall_docker
